#-------------------------
# My-GitHunAction-Basics
#-------------------------

name: My-GitHubAction-Basics
env:
  APPLICATION_NAME: "My Pytest"
  DEPLOY_PACKAGE_NAME: "pytest-deploy-ver-${{ github.sha }}"
  

on:
  push:
    branches:
      - master

jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message In Testing
        run: echo "Hello World From Testing job"
        
      - name: Execute few command
        run: |
          echo "Print Message One"
          echo "Print Message Two"
          echo "Application name: ${{ env.APPLICATION_NAME }}"
          
      - name: List Current Folder
        run: ls -la
        
      - name: Git clone my repo
        uses: action/checkout@1

      - name: List Current Folder
        run: ls -la
      
        

  my_deploy:
    runs-on: ubuntu-latest
    needs: my_testing
    steps:
      - name: Print Hello Message In Deploy
        run: echo "Hello World From Deploy job"

      - name: Print Deployment Package
        run: echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
