#-------------------------
# My-GitHunAction-Basics
#-------------------------

name: My-GitHubAction-Basics

on:
  push:
    branches:
      - master

jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message In Testing
        run: echo "Hello World From Testing job"

  my_deploy:
    runs-on: ubuntu-latest
    needs: my_testing
    steps:
      - name: Print Hello Message In Deploy
        run: echo "Hello World From Deploy job"
